# Generated by Django 4.2 on 2023-05-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
