# Generated by Django 4.2 on 2023-06-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uww', '0002_alter_tournament_address_alter_tournament_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='image',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
    ]
