# Generated by Django 4.2 on 2023-06-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uww', '0003_tournament_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='image',
            field=models.FileField(upload_to='img/'),
        ),
    ]
